<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5NC6EFS" failures="1" tests="5" name="testSauceDemo.TestValidCompleteFlow" time="23.434" errors="0" timestamp="2024-08-09T23:44:44 IST" skipped="0">
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="validloginpage" time="6.749"/>
  <system-out/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="addProductToCart" time="8.683"/>
  <system-out/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="enterUserInfo" time="6.594"/>
  <system-out/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="Checkout" time="1.346"/>
  <system-out/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="completeCheckout" time="0.062">
    <failure message="expected [Checkout: Complete!] but found [CHECKOUT: COMPLETE!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Checkout: Complete!] but found [CHECKOUT: COMPLETE!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at pagefiles_SauceDemo.CompleteCheckout.ValidateCheckout(CompleteCheckout.java:34)
at testSauceDemo.TestValidCompleteFlow.completeCheckout(TestValidCompleteFlow.java:103)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- completeCheckout -->
  <system-out/>
</testsuite> <!-- testSauceDemo.TestValidCompleteFlow -->
